### ISSUE TITLE
Persistent Error message when running ObsidianFollowLink function

### ISSUE THREAD

**Issue by mesa123123** [epwalsh/obsidian.nvim#162]
### 🐛 Describe the bug

Shouldn't be too hard to reconfigure but I've mapped my "gf" keys to something else and the obsidian follow link fucntionality to "<leader>kkl" but every time I run it I get:

![image](https://github.com/epwalsh/obsidian.nvim/assets/22901019/a6d3709f-c9a8-457c-955b-324b185d3a30)

which is an annoying warning as I'm aware I've remapped everything, is there a way to turn this off?

### Versions

Obsidian v1.12.20

NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

**Comment by epwalsh** [comment]
Hey @mesa123123, yes this was a newly added feature. You can avoid this warning by putting the following in your Obsidian.nvim config:

```lua
mappings = {}
```

Or let Obsidian.nvim set up the follow link for you:

```lua
mappings = {
  ["kkl"] = require("obsidian.mapping").gf_passthrough(),
}
```

**Comment by mesa123123** [comment]
Oh briliant! Thanks heaps I was a little unclear on how to do it

**Comment by epwalsh** [comment]
No worries, I should clarify this in the README!

**Comment by mesa123123** [comment]
Might be a goer!
Say something like "if you want to handle your own mappings you can do the `mappings = {}` function?"

**Comment by epwalsh** [comment]
Done: 96d20ed

**Comment by mertnuhoglu** [comment]
I put the `mappings = {}` line into default options. But I still get the error message constantly.

I use `lazy.nvim` to manage plugins. Here is the configuration file for `obsidian.nvim`:

```lua
return {
  "epwalsh/obsidian.nvim",
  lazy = false,
  event = { "BufReadPre /Users/mertnuhoglu/gdrive/grsm/opal/docs-grsm/pages/**.md" },
  dependencies = {
    "nvim-lua/plenary.nvim",
  },
  opts = {
    dir = "~/gdrive/grsm/opal/docs-grsm/pages",  -- no need to call 'vim.fn.expand' here
    mappings = {},
  },
}
```

If instead of empty mappings, I put the following line:

```lua
mappings = {
  ["kkl"] = require("obsidian.mapping").gf_passthrough(),
}
```

Then I get the following error message, when neovim starts:

```
Failed to load `plugins.obsidian`                                                                                                                                                                                                               
/Users/mertnuhoglu/.config/nvim/lua/plugins/obsidian.lua:18: module 'obsidian.mapping' not found:                                                                                                                                               
^Ino field package.preload['obsidian.mapping']                                                                                                                                                                                                  
cache_loader: module obsidian.mapping not found                                                                                                                                                                                                 
cache_loader_lib: module obsidian.mapping not found                                                                                                                                                                                             
^Ino file './obsidian/mapping.lua'                                                                                                                                                                                                              
^Ino file '/usr/local/share/luajit-2.1.0-beta3/obsidian/mapping.lua'                                                                                                                                                                            
^Ino file '/usr/local/share/lua/5.1/obsidian/mapping.lua'                                                                                                                                                                                       
^Ino file '/usr/local/share/lua/5.1/obsidian/mapping/init.lua'                                                                                                                                                                                  
^Ino file './obsidian/mapping.so'                                                                                                                                                                                                               
^Ino file '/usr/local/lib/lua/5.1/obsidian/mapping.so'                                                                                                                                                                                          
^Ino file '/usr/local/lib/lua/5.1/loadall.so'                                                                                                                                                                                                   
^Ino file './obsidian.so'                                                                                                                                                                                                                       
^Ino file '/usr/local/lib/lua/5.1/obsidian.so'                                                                                                                                                                                                  
^Ino file '/usr/local/lib/lua/5.1/loadall.so'                                                                                                                                                                                                   
# stacktrace:                                                                                                                                                                                                                                   
  - ~/.config/nvim/lua/plugins/obsidian.lua:18                                                                                                                                                                                                  
  - ~/.config/nvim/lua/config/lazy.lua:9                                                                                                                                                                                                        
Press ENTER or type command to continue                                                                                                                                                                                                         
  - ~/prj/private_dotfiles/.config/nvimconfigs/lazyvim/init.lua:3   
```

**Comment by epwalsh** [comment]
@mertnuhoglu looks like a bit of a chicken and egg problem with lazy.nvim. I've opened #205 to update the recommendation on how to configure mappings. Basically you'll just need to the change the `mappings` part of your config to this:

```lua
mappings = {
  ["kkl"] = {
    action = function()
      return require("obsidian").util.gf_passthrough()
    end,
    opts = { noremap = false, expr = true, buffer = true },
  },
}
```

**Comment by DylanMartin0930** [comment]
Hey im still getting the error even with @epwalsh fix posted on Sept 25th, it also occurs when i set mappins to just `mappings = {}`:
```
[Obsidian] Obsidian cannot override 'gf' keybinding since 'gf' has been set by:
 <Cmd>lua require("which-key").show("g", {mode = "n", auto = true})<CR>
To avoid this warning remove the 'gf' mapping in the 'mappings' section of your
 obsidian.nvim config.
```
heres my obsidian config: 
```
return {
	"epwalsh/obsidian.nvim",
	lazy = false,

	event = { "BufReadPre", "BufNewFile" }, -- to disable, comment this out
	dependencies = {
		-- Required.
		"nvim-lua/plenary.nvim",

		-- see below for full list of optional dependencies 👇
	},
	config = function()
		local obsidian = require("obsidian")

		obsidian.setup({
			opts = {
				dir = "~/Documents/Obsidian Vault",
				completion = {
					-- If using nvim-cmp, otherwise set to false
					nvim_cmp = true,
					-- Trigger completion at 2 chars
					min_chars = 2,
					-- Where to put new notes created from completion. Valid options are
					--  * "current_dir" - put new notes in same directory as the current buffer.
					--  * "notes_subdir" - put new notes in the default notes subdirectory.
					new_notes_location = "current_dir",

					-- Whether to add the output of the node_id_func to new notes in autocompletion.
					-- E.g. "[[Foo" completes to "[[foo|Foo]]" assuming "foo" is the ID of the note.
					prepend_note_id = false,
				},
				mappings = {
					["kkl"] = {
						action = function()
							return require("obsidian").util.gf_passthrough()
						end,
						opts = { noremap = false, expr = true, buffer = true },
					},
				},
			},
		})
	end,
}

```
and this is my which key config, if it helps for context:
```
return {
	"folke/which-key.nvim",
	event = "VeryLazy",
	init = function()
		vim.o.timeout = true
		vim.o.timeoutlen = 500
	end,
	opts = {
		-- your configuration comes here
		-- or leave it empty to use the default settings
		-- refer to the configuration section below
		-- require("which-key").show("g", {mode = "n", auto = true})<CR>
	},
}
```

**Comment by epwalsh** [comment]
@DylanMartin0930 can you try with the latest commit?

**Comment by DylanMartin0930** [comment]
its fixed on my end now, thanks!

**Comment by twopats** [comment]
> its fixed on my end now, thanks!

Hello, I was still curious of what the fix ends up being? I have tried remapping to "go" instead of "gf" in my obsidian.nvim config. The remap functions as expected, but the warning that obsidian is attempting to override whichkey still remains.

Thanks very much for your time.

**Comment by epwalsh** [comment]
@twopats is your obsidian.nvim installation up-to-date? What's the exact message you see?

**Comment by twopats** [comment]
> @twopats is your obsidian.nvim installation up-to-date? What's the exact message you see?

@epwalsh Got the exact same error message as Dylan above. Updated to latest version and it problem is solved. Thanks a bunch 🙏 🙏
