### ISSUE TITLE
Front matter alias duplicates itself on save.

### ISSUE THREAD

**Issue by rileyhawk1417** [epwalsh/obsidian.nvim#341]
### 🐛 Describe the bug

When saving a file the `alias` tag value duplicates itself. Noticed that it happened a few times on that particular file. Although I think its just an edge case. I took a screen recording of the bug happening.

https://github.com/epwalsh/obsidian.nvim/assets/42723553/bdcf182e-ef10-4098-8c74-4c1278e0d6c2

### Versions

```bash
❯ nvim --version
nvim --headless -c 'lua require("obsidian").info()' -c q
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1702233742

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
[obsidian.nvim (v2.7.0)] Commit SHA: e2d6ce7b07941b0788177e1297699ad99c1470dc
[plenary.nvim] Commit SHA: 663246936325062427597964d81d30eaa42ab1e4
[nvim-cmp] Commit SHA: 538e37ba87284942c1d76ed38dd497e54e65b891
[telescope.nvim] Commit SHA: d90956833d7c27e73c621a61f20b29fdb7122709
ripgrep 14.1.0%
```

**Comment by epwalsh** [comment]
Hey @rileyhawk1417, I just pushed a fix in https://github.com/epwalsh/obsidian.nvim/commit/3b4c672e5b5246ba836e6bf52a9ef39c089516f5.

**Comment by rileyhawk1417** [comment]
Hi @epwalsh thanks for the fix its working :)
Have been daily driving Neovim so having a plugin for note taking is a game changer 😄

**Comment by pranavTripathi02** [comment]
Hi @epwalsh, this issue still seems to occur if there is whitespace following the header without quotes
`# Heading<space> `  duplicates the alias while `# Heading` does not and neither does `# "Heading<space>"`

**Comment by epwalsh** [comment]
Hey @pranavTripathi02, thanks for letting me know. I just fixed that in d1c8162.
